#!/usr/bin/env python
#
# statmon.py -- Flexible Gen2 status monitor.
#
# E. Jeschke
# T. Inagaki
# R. Kackley
#
"""
Usage:
    statmon.py --monport=NNNNN --plugins=X,Y,Z
"""
# stdlib imports
import sys, os
import threading
import queue as Queue
from argparse import ArgumentParser

import statmon.version
moduleHome = os.path.split(sys.modules['statmon.version'].__file__)[0]
sys.path.insert(0, moduleHome)
pluginHome = os.path.join(moduleHome, 'plugins')
sys.path.insert(0, pluginHome)

from g2base import Task
from g2base.remoteObjects import remoteObjects as ro
from g2base.remoteObjects import Monitor
from g2cam.status.stream import StatusStream

# Subaru python stdlib imports
import g2client.soundsink as SoundSink

from ginga import toolkit
toolkit.use('qt5')
from ginga.gw import Widgets
from ginga.misc import ModuleManager, Settings, log

# Local application imports
from statmon.Model import StatusModel
from statmon.View import Viewer
from statmon.Control import Controller

defaultServiceName = 'statmon'
version = "20211207.0"

default_layout = ['seq', {},
                  ['vbox', dict(name='toplvl', width=1700, height=1000),
                   ['hbox', dict(name='menubox', stretch=0)],
                   ['vbox', dict(stretch=1),
                    ['ws', dict(name='top', show_tabs=False,
                                height=120, stretch=0), ],
                    ['hpanel', dict(height=1000, stretch=1),
                     # ['vbox', dict(width=350, spacing=4, stretch=0),
                     #  ['ws', dict(name='left1', height=75, stretch=0,
                     #              show_tabs=False), ],
                     #  ['ws', dict(name='left2', height=350, stretch=0,
                     #              show_tabs=False), ],
                     #  ['ws', dict(name='left3', height=450, stretch=3,
                     #              show_tabs=False),],
                     #  ['ws', dict(name='left4', height=80, stretch=1,
                     #              show_tabs=False),],
                     #  ['ws', dict(name='left5', height=80, stretch=1,
                     #              show_tabs=False),],
                     #  ],
                     ['vbox', dict(width=320, spacing=4, stretch=5),
                      ['ws', dict(name='telconf_info', height=500, stretch=5,
                                  show_tabs=False), ],
                      ['ws', dict(name='azlimit_info', height=80, stretch=1,
                                  show_tabs=False), ],
                      ['ws', dict(name='ellimit_info', height=80, stretch=1,
                                  show_tabs=False), ],
                      ['ws', dict(name='rotlimit_info', height=80, stretch=1,
                                  show_tabs=False), ],
                      ['ws', dict(name='middle16', height=160, stretch=2,
                                  show_tabs=False), ],
                     ],
                     ['vbox', dict(width=300, spacing=4),
                      ['ws', dict(name='pointing_info', height=75, stretch=0,
                                  show_tabs=False), ],
                       ['ws', dict(name='slewtime_info', height=25, stretch=0,
                                   show_tabs=False), ],
                       ['ws', dict(name='domeff_info', height=25, stretch=0,
                                   show_tabs=False), ],
                       ['ws', dict(name='target_info', height=150, stretch=0,
                                   show_tabs=False), ],
                       ['ws', dict(name='callamp_info', height=50, stretch=0,
                                   show_tabs=False), ],
                       ['ws', dict(name='calprobe_info', height=25, stretch=0,
                                   show_tabs=False), ],
                       ['ws', dict(name='tsclogin_info', height=80, stretch=0,
                                   show_tabs=False), ],
                       ['ws', dict(name='middle25', height=225, stretch=2,
                                   show_tabs=False), ],
                     ],
                     ['vbox', dict(width=500, stretch=1),
                      ['ws', dict(name='right', width=350, stretch=0), ],
                      ['ws', dict(name='alarm_info', width=350, stretch=3,
                                  show_tabs=False), ],
                     ],
                    ],
                    ['ws', dict(name='bottom', show_tabs=False,
                                height=50, stretch=0), ],
                    ],
                   ['hbox', dict(name='statusbox', stretch=0)],
                   ]
                  ]

plugins = [
    # pluginName, moduleName, className, workspaceName, tabName
    ('radec', 'RaDec', 'RaDec', 'top', ''),
    ('times', 'RaDec', 'Times', 'bottom', ''),
    ('statusable', 'StatusTablePlugin', 'StatusTablePlugin',
     'right', 'StatTable'),
    ('debug', 'Debug', 'Debug', 'right', "Debug"),
    ('state', 'StatePlugin', 'StatePlugin', 'pointing_info', ''),
    # ('plot', 'PlotPlugin', 'PlotPlugin', 'left2', ''),
    # ('guidingimage', 'GuidingImage', 'GuidingImage', 'left3','' ),
    # ('probe1limit', 'LimitPlugin', 'Probe1LimitPlugin', 'left4','' ),
    # ('probe2limit', 'LimitPlugin', 'Probe2LimitPlugin', 'left5','' ),
    ('telescope', 'TelescopePlugin', 'TelescopePlugin', 'telconf_info',''),
    ('azlimit', 'LimitPlugin', 'AzLimitPlugin', 'azlimit_info', ''),
    ('ellimit', 'LimitPlugin', 'ElLimitPlugin', 'ellimit_info', ''),
    ('rotlimit', 'LimitPlugin', 'RotLimitPlugin', 'rotlimit_info', '' ),
    ('tsccontrol', 'TscControlPlugin', 'TscControlPlugin', 'tsclogin_info', ''),
    ('domeff', 'DomeffPlugin', 'DomeffPlugin', 'domeff_info', ''),
    ('cal', 'CalPlugin', 'CalPlugin', 'callamp_info', ''),
    ('calprobe', 'CalprobePlugin', 'CalprobePlugin', 'calprobe_info', ''),
    ('target', 'TargetPlugin', 'TargetPlugin', 'target_info', ''),
    ('alarm', 'Alarm', 'Alarm', 'alarm_info', ''),
    ]

class StatMon(Controller, Viewer):

    def __init__(self, logger, threadPool, module_manager, settings,
                 soundsink, ev_quit, model):

        self.soundsink = soundsink

        Viewer.__init__(self, logger, ev_quit)
        Controller.__init__(self, logger, threadPool, module_manager,
                            settings, ev_quit, model)

    def play_soundfile(self, filepath, format=None, priority=20):
        self.soundsink.playFile(filepath, format=format,
                                priority=priority)

    def add_menus(self):
        menubar = Widgets.Menubar()
        self.w.menubox.add_widget(menubar, stretch=0)

        # create a File pulldown menu, and add it to the menu bar
        filemenu = menubar.add_name("File")

        filemenu.add_separator()

        item = filemenu.add_name("Quit")
        item.add_callback('activated', self.quit)

        # create a Option pulldown menu, and add it to the menu bar
        ## optionmenu = menubar.add_name("Option")

    def add_statusbar(self):
        self.w.status = Widgets.StatusBar()
        self.w.statusbox.add_widget(self.w.status, stretch=1)


def main(options, args):

    # Create top level logger.
    svcname = options.svcname
    logger = log.get_logger(svcname, options=options)

    # Initialize remote objects subsystem.
    try:
        ro.init([options.gen2host])

    except ro.remoteObjectError as e:
        logger.error("Error initializing remote objects subsystem: %s" % \
                     str(e))
        sys.exit(1)

    ev_quit = threading.Event()

    # make a name for our monitor
    myMonName = '%s-%s-%d.mon' % (svcname, ro.get_myhost(short=True),
                                  options.monport)

    # monitor channels we are interested in
    channels = options.monchannels.split(',')

    # Create a local pub sub instance
    mymon = Monitor.Monitor(myMonName, logger,
                            numthreads=options.numthreads)

    threadPool = mymon.get_threadPool()

    sndsink = SoundSink.SoundSource(monitor=mymon, logger=logger,
                                    channels=['sound'])

    # Get settings folder
    if 'CONFHOME' in os.environ:
        basedir = os.path.join(os.environ['CONFHOME'], svcname)
    else:
        basedir = os.path.join(os.environ['HOME'], '.' + svcname)
    if not os.path.exists(basedir):
        os.mkdir(basedir)
    prefs = Settings.Preferences(basefolder=basedir, logger=logger)

    mm = ModuleManager.ModuleManager(logger)

    # Add any custom modules
    if options.modules:
        modules = options.modules.split(',')
        for mdlname in modules:
            #self.mm.loadModule(name, pfx=pluginconfpfx)
            self.mm.loadModule(name)

    model = StatusModel(logger)

    # Start up the control/display engine
    statmon = StatMon(logger, threadPool, mm, prefs,
                      sndsink, ev_quit, model)

    # Build desired layout
    statmon.build_toplevel(layout=default_layout)
    statmon.w.root.set_title("StatMon")
    for w in statmon.ds.toplevels:
        w.show()

    for pluginName, moduleName, className, wsName, tabName in plugins:
        statmon.load_plugin(pluginName, moduleName, className,
                            wsName, tabName)

    statmon.update_pending()

    # Did user specify geometry
    if options.geometry:
        statmon.set_geometry(options.geometry)

    server_started = False

    # Create receiver and start it
    try:
        # Startup monitor threadpool
        mymon.start(wait=True)

        # start_server is necessary if we are subscribing, but not if only
        # publishing
        mymon.start_server(wait=True, port=options.monport)
        server_started = True

        # Compute the union of channels supplied on command-line with
        # channels registered by plugins
        #allChannels = set(channels) | model.channels
        # status now handled via different mechanism
        allChannels = (set(channels) | model.channels) - set(['status'])
        print("channels are", allChannels)

        if options.monitor:
            # subscribe our monitor to the central monitor hub.
            # Monitor.subscribe_remote requires that the channels be
            # supplied as a Python list, so convert allChannels from a
            # set to a list when we supply it to Monitor.subscribe_remote.
            mymon.subscribe_remote(options.monitor, list(allChannels), {})
            # publishing for remote command executions
            mymon.publish_to(options.monitor, ['sound'], {})

        # Register channel subscription callback
        logger.info('subscribe to channels {}'.format(allChannels))
        mymon.subscribe_cb(model.arr_channel, allChannels)

        settings = prefs.create_category('status')
        st_stream = None
        try:
            settings.load()

            # set up the status stream interface
            st_stream = StatusStream(host=settings.get('stream_host'),
                                     username=settings.get('stream_user'),
                                     password=settings.get('stream_pass'),
                                     logger=logger)
            st_stream.connect()

        except Exception as e:
            logger.error("Error setting up status stream: {}".format(e),
                         exc_info=True)

        # intermediary queue
        status_q = Queue.Queue()

        # stream producer puts updates on the queue
        task1 = Task.FuncTask2(st_stream.subscribe_loop, ev_quit, status_q)
        task1.init_and_start(statmon)

        # stream consumer takes them and updates the status cache
        task2 = Task.FuncTask2(model.consume_stream, ev_quit, status_q)
        task2.init_and_start(statmon)

        # Create our remote service object
        ctrlsvc = ro.remoteObjectServer(svcname=options.svcname,
                                        obj=statmon,
                                        method_list=['close_plugin',
                                                     'close_all_plugins'],
                                        logger=logger, ev_quit=ev_quit,
                                        port=options.port,
                                        usethread=True,
                                        threadPool=threadPool)

        logger.info("Starting statmon service.")
        ctrlsvc.ro_start()

        try:
            # Main loop to handle GUI events
            statmon.mainloop(timeout=0.001)

        except KeyboardInterrupt:
            logger.error("Received keyboard interrupt!")

    finally:
        logger.info("Shutting down...")

        statmon.close_all_plugins()
        statmon.stop()
        ctrlsvc.ro_stop(wait=True)
        mymon.stop_server(wait=True)
        mymon.stop(wait=True)

    sys.exit(0)


if __name__ == "__main__":

    # Parse command line options
    argprs = ArgumentParser(description="Gen2 Status Monitor")

    argprs.add_argument('-f', "--config", dest="configfile", default=None,
                        help="Specify configuration file")
    argprs.add_argument("--display", dest="display", metavar="HOST:N",
                        help="Use X display on HOST:N")
    argprs.add_argument("-g", "--geometry", dest="geometry",
                        metavar="GEOM", default="+20+100",
                    help="X geometry for initial size and placement")
    argprs.add_argument("--gen2host", dest="gen2host",
                        metavar="HOST",
                        default=os.environ.get('GEN2HOST', "localhost"),
                        help="Connect to Gen2 HOST")
    argprs.add_argument("--modules", dest="modules", metavar="NAMES",
                        help="Specify additional modules to load")
    argprs.add_argument("--monitor", dest="monitor", metavar="NAME",
                        default='monitor',
                        help="Synchronize from monitor named NAME")
    argprs.add_argument("--monchannels", dest="monchannels",
                        default='alarm', metavar="NAMES",
                        help="Specify monitor channels to subscribe to")
    argprs.add_argument("--monport", dest="monport", type=int,
                        help="Register monitor using PORT", metavar="PORT")
    argprs.add_argument("--numthreads", dest="numthreads", type=int,
                        default=30,
                        help="Start NUM threads in thread pool", metavar="NUM")
    argprs.add_argument("--plugins", dest="plugins", metavar="NAMES",
                        help="Specify additional plugins to load")
    argprs.add_argument("--port", dest="port", type=int, default=None,
                        help="Register using PORT", metavar="PORT")
    argprs.add_argument("--svcname", dest="svcname", metavar="NAME",
                        default=defaultServiceName,
                        help="Register using NAME as service name")
    log.addlogopts(argprs)

    (options, args) = argprs.parse_known_args(sys.argv[1:])

    if options.display:
        os.environ['DISPLAY'] = options.display

    if options.monport is None:
        argprs.error("Please provide a value for --monport")

    main(options, args)
